export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAIL = 'USER_LIST_FAIL';

export const USERS_REPOS_REQUEST = 'USERS_REPOS_REQUEST';
export const USERS_REPOS_SUCCESS = 'USERS_REPOS_SUCCESS';
export const USERS_REPOS_FAIL = 'USERS_REPOS_FAIL';
export const USERS_REPOS_RESET = 'USERS_REPOS_RESET';

export const USER_INFO_REQUEST = 'USER_INFO_REQUEST';
export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS';
export const USER_INFO_FAIL = 'USER_INFO_FAIL';
export const USER_INFO_RESET = 'USER_INFO_RESET';
